repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: pretty-format-json
        name: 'Pretty format JSON'
        args:
          - '--no-sort-keys'
          - '--autofix'
          - '--indent=2'
      - id: trailing-whitespace
        name: 'Fix trailing whitespace'
      - id: end-of-file-fixer
        name: 'Fix missing EOF'
      - id: check-executables-have-shebangs
        name: 'Check exeutables for shebangs'
      - id: check-merge-conflict
        name: 'Check for merge conflict fragments'
      - id: check-case-conflict
        name: 'Check for filesystem character case conflicts'
      - id: detect-private-key
        name: 'Check for Python style guideline violations'
      - id: check-json
        name: 'Validate JSON'
      - id: check-ast
        name: 'Check Python abstract syntax tree'
  - repo: 'https://github.com/asottile/reorder_python_imports'
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        name: 'Reorder Python imports'
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
    - id: black
      name: 'Ruthlessly format Python'
      language_version: python3.7
      args:
        - '--line-length=79'
