[tool.poetry]
name = "humps"
version = "3.5.3"
description = "Convert strings (and dictionary keys) between snake case, camel case and pascal case in Python."
authors = ["Nick Ficano <nficano@gmail.com>"]
license = "The Unlicense (Unlicense)"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"
pytest = "^6.2.5"
pylint = "^2.12.2"
flake8 = "^4.0.1"
pytest-cov = "^3.0.0"
pathlib2 = "^2.3.6"
scandir = "^1.10.0"
coveralls = "^3.3.1"
twine = "^3.7.1"
ipython = "^7.31.1"
Sphinx = "^4.3.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
